### ISSUE TITLE
>,<,>=,<=

### ISSUE THREAD

**Issue by a-alex-l** [featdd/FractionClass#1]
Totally wrong implementation!

**Comment by featdd** [comment]
Hi @a-alex-l,

this code was a task from my time at school and is almost 10 years old, I don't even do any cpp today.
Please feel free to give an explanation of whats wrong or do a pull request.

Greetings
Daniel

**Comment by a-alex-l** [comment]
Hello.
### This
return (this->numerator * (this->denominator * fraction.getDenominator())) < (fraction.getNumerator() * (this->denominator * fraction.getDenominator()));
### should be replaced with
return (this->numerator * fraction.getDenominator()) < (fraction.getNumerator() * this->denominator);

**Comment by featdd** [comment]
Hi @a-alex-l,

solved in 25c9ba65cdcf30843f56b61b369382255b824cd9

Greetings
Daniel
